### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by simon-bourque**

### CODE REVIEW

**Comment by simon-bourque** [comment]
Yup! I'll wait for other peoples opinions before merging.  Then ill start making issues for people to work on if they want

**Comment by Gabbell** [comment]
Could we add priority? It's a shame we won't be able to sort by priority but I still think it would be useful.

**Comment by simon-bourque** [comment]
wanted to ask you about that

**Comment by jeromepl** [comment]
I disagree with having priority in the template, it should instead be added as a tag to issues

**Comment by jeromepl** [comment]
Also, adding a 'Motivation' section to tasks could be useful

**Comment by simon-bourque** [comment]
I mentioned adding a critical label to @Gabbell but having all the priorites as labels works for me too

**Comment by simon-bourque** [comment]
What would someone put in the motivation section? I was thinking they would put all the info in the description

**Comment by jeromepl** [comment]
Here is my motivation for the 'motivation' section ( 😆 ): in the past weeks, I have tried to understand what some of your PRs were for, without success. If I don't know why we are doing it, then I can't really help to make it happen and this applies to both new issues and PR reviews.

**Comment by Gabbell** [comment]
I agree with the label for priority and I feel like whatever motivation we would have, we would put it in the description. When we'll have actual issues it'll be easier to follow than just random PRs :P

**Comment by jeromepl** [comment]
True, motivation could just be included in description.

We should also be mentionning issues in all related commits from now on. Just need to add a `#[issue-nb]` on the last line of each commit.

**Comment by simon-bourque** [comment]
@Gabbell I think if we don't put the motivation section then people will forget to mention it in the description

**Comment by simon-bourque** [comment]
@jeromepl we usually add the #issue_num its just that we didn't have any issues to reference yet lol

**Pull request merged**
